# Generated by Django 5.2.14 on 2026-06-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tourpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Kaleem Overseas Consultants Pvt. Ltd.', max_length=200)),
                ('tagline', models.CharField(default='Professional Visa Consultancy and Travel Services', max_length=255)),
                ('about_text', models.TextField(default='Trusted visa guidance, appointments, and travel support for clients who want a smooth overseas journey.')),
                ('mission', models.TextField(default='To provide reliable visa consultancy and professional travel services with honesty, clarity, and care.')),
                ('vision', models.TextField(default='To be a trusted name in visit visa and business visa consultancy, travel planning, and customer support.')),
                ('why_choose_us', models.TextField(default='Professional guidance, fast communication, accurate documentation, and premium support.')),
                ('director_name', models.CharField(default='Kaleem Ahmed', max_length=120)),
                ('director_title', models.CharField(default='Owner & Director', max_length=120)),
                ('director_message', models.TextField(default='We focus on practical guidance, honest communication, and dependable service for every client.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('phone', models.CharField(default='', max_length=25)),
                ('email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(default='', max_length=160)),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='city',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='appointment',
            name='country',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visa_type',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='country',
            name='visa_category',
            field=models.CharField(choices=[('visit', 'Visit Visa'), ('business', 'Business Visa')], default='visit', max_length=20),
        ),
        migrations.DeleteModel(
            name='VisaApplication',
        ),
    ]
