# Generated by Django 5.2.14 on 2026-06-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_consultancy_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visa_type',
            field=models.CharField(choices=[('visit', 'Visit Visa'), ('business', 'Business Visa'), ('tour', 'Tour Package'), ('consultation', 'Travel Consultation'), ('other', 'Other')], default='visit', max_length=120),
        ),
    ]
