# Generated by Django 5.2.14 on 2026-06-27 14:39

from django.db import migrations, models


def backfill_appointment_numbers(apps, schema_editor):
    Appointment = apps.get_model("core", "Appointment")

    appointments = Appointment.objects.order_by("created_at", "pk")
    yearly_sequence = {}

    for appointment in appointments:
        year = appointment.created_at.year if appointment.created_at else 2026
        yearly_sequence[year] = yearly_sequence.get(year, 0) + 1
        appointment.appointment_number = f"KOC-{year}{yearly_sequence[year]:04d}"
        if not appointment.status:
            appointment.status = "pending"
        appointment.save(update_fields=["appointment_number", "status"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appointment_visa_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_letter',
            field=models.FileField(blank=True, null=True, upload_to='appointment_letters/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='office_address',
            field=models.TextField(default='Islamabad, Pakistan'),
        ),
        migrations.RunPython(backfill_appointment_numbers, noop_reverse),
    ]
