# Generated by Django 5.2.14 on 2026-06-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment_appointment_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='testimonials/videos/'),
        ),
    ]
