# Generated by Django 5.2.14 on 2026-06-28 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_testimonial_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('visa_type', models.CharField(choices=[('visit', 'Visit Visa'), ('family', 'Family Visa'), ('business', 'Business Visa'), ('tour', 'Tour Package')], max_length=20)),
                ('video', models.FileField(upload_to='success_stories/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='success_stories/thumbnails/')),
                ('description', models.TextField()),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Success Story',
                'verbose_name_plural': 'Success Stories',
                'ordering': ['-upload_date', '-pk'],
            },
        ),
    ]
